### PR TITLE
normalized jump

### PR DESCRIPTION
**Pull request by jflowbflow**
work around for a lower jump force

### CODE REVIEW

**Comment by JJL772** [comment]
Thanks for the patch!
Got a couple of questions though. Have you tested this in game? And would it be possible to turn the jump force into a convar again?

**Comment by jflowbflow** [comment]
Yea you can turn it into a convar, my friend just decided to take it out. Tbh, I'm new to lua and vscripting so idk what the purpose of a convar is. But the player think to call normalize jump does work, and because its delayed by .02 seconds it gets off the ground thereby bypassing the hardcoded VR no jump.
-------- Original message --------From: Jeremy Lorelli <notifications@github.com> Date: 4/9/20  2:09 PM  (GMT-05:00) To: JJL772/half-life-alyx-scripts <half-life-alyx-scripts@noreply.github.com> Cc: jflowbflow <joshuabgad@gmail.com>, Author <author@noreply.github.com> Subject: Re: [JJL772/half-life-alyx-scripts] normalized jump (#1) 
Thanks for the patch!
Got a couple of questions though. Have you tested this in game? And would it be possible to turn the jump force into a convar again?

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/JJL772/half-life-alyx-scripts/pull/1#issuecomment-611673658",
"url": "https://github.com/JJL772/half-life-alyx-scripts/pull/1#issuecomment-611673658",
"name": "View Pull Request"
},
"description": "View this Pull Request on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by JJL772** [comment]
Alright, I'll merge it into a separate branch and make some small changes to it.
Thanks!

**Comment by JJL772** [comment]
merged into dev

**Pull request closed without merging**
